# Generated by Django 3.0.2 on 2020-01-09 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
    ]
